name: DockerVulnerabilities
on:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"
       
jobs:
    docker-analysis:
        name: Trivy analysis for Docker image
        runs-on: ubuntu-latest

        steps:
            - uses: step-security/harden-runner@v2
              if: ${{ github.event.repository.visibility == 'public' }}
              with:
               disable-sudo: false
               egress-policy: audit
            
            - uses: actions/checkout@v4
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              id: buildx

            - name: Build and load
              run: |
                    docker buildx bake \
                    --set "*.cache-from=type=gha" \
                    --set "*.platform=linux/amd64" \
                    --builder ${{ steps.buildx.outputs.name }} \
                    -f docker-compose.yml \
                    --load \
                    eth bnb
              env:
                DOCKER_TAG: analysis-latest
        
            - name: Scan vulnerabilities ethereum node image
              uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
              with:           
                image-ref: 'vsnw3/ethereum-node:analysis-latest'
                format: 'sarif'
                output: 'trivy-vision-ethereum-node-results.sarif'
                severity: 'CRITICAL,HIGH'
            
            - name: Upload Trivy scan results for ethereum node to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                category: 'vision-ethereum-node'
                sarif_file: 'trivy-vision-ethereum-node-results.sarif'
