name: Publish dev release
on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    if: github.repository == 'vision-web3/ethereum-contracts'
    secrets: 'inherit'
    with:
      tag: development
      architecture: amd64
      environment: main
      cache_enabled: true

  test:
    needs: publish-docker
    uses: vision-web3/e2e-testing/.github/workflows/ci.yaml@main
